name: Generate Session Secret

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read
  actions: read
  secrets: write # Correct syntax for permissions

jobs:
  generate-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Random Session Secret
        id: generate_secret
        run: echo "SESSION_SECRET=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - name: Save Secret to GitHub Repository Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PUBKEY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key)
          KEY_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key_id)
          ENCRYPTED_SECRET=$(echo -n "${{ env.SESSION_SECRET }}" | openssl pkeyutl -encrypt -pubin -inkey <(echo "$PUBKEY") | base64)
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"encrypted_value\":\"$ENCRYPTED_SECRET\",\"key_id\":\"$KEY_ID\"}" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/SESSION_SECRET

      - name: Output Debug Message
        run: echo "Session secret generated and stored successfully!"
