name: Test Public Key

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Public Key
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          PUBKEY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key)
          echo "Public Key: $PUBKEY"
