name: Store Session Secret

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  store-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

     - name: Generate and Encrypt Session Secret
  id: encrypt
  env:
    GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  run: |
    # Define your session secret
    SESSION_SECRET="oKx5M9yqiILBd37qRDDFYWQdWca0qIkONPBbO/DpdGc="

    # Fetch the public key and key ID
    PUBKEY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key)
    KEY_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key_id)

    # Write the public key to a PEM file
    echo "-----BEGIN PUBLIC KEY-----\n$PUBKEY\n-----END PUBLIC KEY-----" > public.pem

    # Debug: Verify public.pem content
    echo "Public Key File Contents:"
    cat public.pem

    # Encrypt the session secret
    ENCRYPTED_SECRET=$(echo -n "$SESSION_SECRET" | openssl pkeyutl -encrypt -pubin -inkey public.pem | base64)

    # Debug: Verify encryption
    echo "Encrypted Secret: $ENCRYPTED_SECRET"

    # Set outputs for later steps
    echo "encrypted_secret=$ENCRYPTED_SECRET" >> $GITHUB_ENV
    echo "key_id=$KEY_ID" >> $GITHUB_ENV
