name: Generate and Store Secret

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  generate-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Random Secret
        id: generate_secret
        run: echo "SESSION_SECRET=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - name: Fetch Public Key
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PUBKEY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key)
          echo "Public Key: $PUBKEY"

      - name: Store Secret in Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PUBKEY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key)
          KEY_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key_id)
          ENCRYPTED_SECRET=$(echo -n "${{ env.SESSION_SECRET }}" | openssl pkeyutl -encrypt -pubin -inkey <(echo "$PUBKEY") | base64)
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"encrypted_value\":\"$ENCRYPTED_SECRET\",\"key_id\":\"$KEY_ID\"}" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/SESSION_SECRET
