name: Store Session Secret

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  store-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Generate and Encrypt Session Secret
        id: encrypt
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          SESSION_SECRET="oKx5M9yqiILBd37qRDDFYWQdWca0qIkONPBbO/DpdGc="
          PUBKEY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key)
          KEY_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key_id)
          ENCRYPTED_SECRET=$(echo -n "$SESSION_SECRET" | openssl pkeyutl -encrypt -pubin -inkey <(echo "-----BEGIN PUBLIC KEY-----\n$PUBKEY\n-----END PUBLIC KEY-----") | base64)
          echo "::set-output name=encrypted_secret::$ENCRYPTED_SECRET"
          echo "::set-output name=key_id::$KEY_ID"

      - name: Store Encrypted Secret
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"encrypted_value\":\"${{ steps.encrypt.outputs.encrypted_secret }}\",\"key_id\":\"${{ steps.encrypt.outputs.key_id }}\"}" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/SESSION_SECRET
