name: Generate Session Secret

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Random Session Secret
        run: echo "SESSION_SECRET=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - name: Save Secret to GitHub Repository Secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"encrypted_value\":\"${SESSION_SECRET}\",\"key_id\":\"$(curl -s -H \\\"Authorization: token $GITHUB_TOKEN\\\" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key | jq -r .key_id)\"}" \
          https://api.github.com/repos/${{ github.repository }}/actions/secrets/SESSION_SECRET

      - name: Output Session Secret
        run: echo "Your generated SESSION_SECRET: $SESSION_SECRET"
