name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Run the database initialization script
    - name: Initialize the database
      run: python initialize_db.py

    # Run the query script
    - name: Run tests
      run: python query_cards.py
